channels:
- conda-forge
- nodefaults
dependencies:
- python=3.11
- pyiron
- pyiron_base=0.10.2
- pyiron_contrib=0.1.18
- coscine
- pyiron_atomistics=0.6.12
- lammps
- iprpy-data
- sphinxdft >=3.0
- sphinxdft-data
- nglview
- seaborn
- pyscal
- jupyterlab
- pyiron-data >=0.0.22
- sqsgenerator
- pymatgen
