channels:
- conda-forge
dependencies:
- python=3.10
- pyiron
- pyiron_base=0.6.1
- pyiron_contrib=0.1.10
- coscine
- pyiron_atomistics=0.3.0
- lammps
- iprpy-data
- sphinxdft >=3.0
- sphinxdft-data
- nglview
- seaborn
- pyscal
- jupyterlab
- pyiron-data >=0.0.22
- sqsgenerator
- pymatgen
